<template>
<div id="blueRowMap">
  <div class="container">
    <div class="box" style="text-align: left; ">
      <h3 class="title">Stake in less than 2 clicks!
        <h4>Write here some kind of instructions!</h4>
      </h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis tellus vitae neque tristique vehicula. Integer lobortis est nec purus tempor lacinia. In hac habitasse platea dictumst. Quisque in mauris eu magna pharetra bibendum. Curabitur euismod libero mauris, et vestibulum libero ultrices sed. Nunc sit amet dui at odio tincidunt porta quis vitae nibh. Cras tincidunt massa sagittis, congue magna sit amet, vulputate massa. Morbi nibh leo, euismod a lorem id, eleifend commodo odio. Donec vitae leo volutpat, ultricies eros sit amet, congue lectus. Fusce iaculis, magna nec fringilla sollicitudin, erat nisi dictum mauris, sit amet rutrum ipsum urna et tortor. Suspendisse turpis sapien, molestie eu luctus quis, mollis sit amet nibh. Nullam facilisis arcu eget commodo sagittis. Donec eu purus ut enim vestibulum egestas non sit amet lorem. Proin at tellus ac nisi gravida mollis. Nullam iaculis diam vel nunc tincidunt, et condimentum orci suscipit. Proin lacus enim, dapibus eu arcu in, mollis luctus ex.</p>
      <p>Vivamus porta fringilla aliquet. Praesent finibus elit sed cursus egestas. Sed ac lectus neque. Donec congue id ante id interdum. Curabitur nunc enim, laoreet quis leo ut, auctor rhoncus velit. Duis velit felis, molestie vitae nibh tincidunt, semper aliquam sapien. Nam a elit dapibus, consectetur massa nec, dictum metus.</p>
      <p>Duis et lacus risus. Fusce vehicula dictum nisl ut tincidunt. Mauris enim sem, convallis consequat tellus sed, tempor suscipit velit. Sed consectetur vel urna id convallis. Aenean non dictum diam. Proin quis vehicula tortor. In vitae erat eu arcu mollis euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin a urna pretium, tincidunt enim sit amet, aliquet dui. Pellentesque tortor quam, iaculis ac justo vitae, elementum varius mauris.</p>
      <p>Praesent sagittis pharetra tellus, et consectetur magna. Fusce dolor tellus, placerat quis ligula at, mollis interdum augue. Duis malesuada ipsum quis augue consequat vestibulum. In suscipit leo orci, at pulvinar urna volutpat a. Etiam at eleifend lorem. Nam at purus bibendum, vestibulum odio eget, efficitur nulla. Curabitur lacinia lacus ac lacus faucibus elementum. Sed tortor dui, facilisis nec nunc ut, pulvinar euismod velit. Proin eu luctus erat, ut faucibus eros. Sed pharetra nulla at est pellentesque, non ornare ligula porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis tellus vitae neque tristique vehicula. Integer lobortis est nec purus tempor lacinia. In hac habitasse platea dictumst. Quisque in mauris eu magna pharetra bibendum. Curabitur euismod libero mauris, et vestibulum libero ultrices sed. Nunc sit amet dui at odio tincidunt porta quis vitae nibh. Cras tincidunt massa sagittis, congue magna sit amet, vulputate massa. Morbi nibh leo, euismod a lorem id, eleifend commodo odio. Donec vitae leo volutpat, ultricies eros sit amet, congue lectus. Fusce iaculis, magna nec fringilla sollicitudin, erat nisi dictum mauris, sit amet rutrum ipsum urna et tortor. Suspendisse turpis sapien, molestie eu luctus quis, mollis sit amet nibh. Nullam facilisis arcu eget commodo sagittis. Donec eu purus ut enim vestibulum egestas non sit amet lorem. Proin at tellus ac nisi gravida mollis. Nullam iaculis diam vel nunc tincidunt, et condimentum orci suscipit. Proin lacus enim, dapibus eu arcu in, mollis luctus ex.</p>
      <p>Vivamus porta fringilla aliquet. Praesent finibus elit sed cursus egestas. Sed ac lectus neque. Donec congue id ante id interdum. Curabitur nunc enim, laoreet quis leo ut, auctor rhoncus velit. Duis velit felis, molestie vitae nibh tincidunt, semper aliquam sapien. Nam a elit dapibus, consectetur massa nec, dictum metus.</p>
      <p>Duis et lacus risus. Fusce vehicula dictum nisl ut tincidunt. Mauris enim sem, convallis consequat tellus sed, tempor suscipit velit. Sed consectetur vel urna id convallis. Aenean non dictum diam. Proin quis vehicula tortor. In vitae erat eu arcu mollis euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin a urna pretium, tincidunt enim sit amet, aliquet dui. Pellentesque tortor quam, iaculis ac justo vitae, elementum varius mauris.</p>
      <p>Praesent sagittis pharetra tellus, et consectetur magna. Fusce dolor tellus, placerat quis ligula at, mollis interdum augue. Duis malesuada ipsum quis augue consequat vestibulum. In suscipit leo orci, at pulvinar urna volutpat a. Etiam at eleifend lorem. Nam at purus bibendum, vestibulum odio eget, efficitur nulla. Curabitur lacinia lacus ac lacus faucibus elementum. Sed tortor dui, facilisis nec nunc ut, pulvinar euismod velit. Proin eu luctus erat, ut faucibus eros. Sed pharetra nulla at est pellentesque, non ornare ligula porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
    </div>
  </div>
</div>
</template>
